# Generated by Django 5.0.2 on 2024-03-12 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blockedusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_content', models.CharField(choices=[('question', 'question'), ('answer', 'answer')], max_length=255)),
                ('reason', models.CharField(choices=[('Spam or Advertising', 'Spam or Advertising'), ('Offensive Language or Harassment', 'Offensive Language or Harassment'), ('Inappropriate Content', 'Inappropriate Content'), ('Misinformation or Fake News', 'Misinformation or Fake News'), ('Impersonation', 'Impersonation'), ('Copyright Infringement', 'Copyright Infringement'), ('Privacy Violation', 'Privacy Violation'), ('Bullying or Intimidation', 'Bullying or Intimidation'), ('Irrelevant or Off-Topic', 'Irrelevant or Off-Topic')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.answer')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.question')),
            ],
        ),
    ]
