# Generated by Django 5.0.2 on 2024-03-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_proof_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proof',
            name='rejected',
        ),
        migrations.AlterField(
            model_name='proof',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], max_length=255),
        ),
    ]
