# Generated by Django 5.0.2 on 2024-03-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_proof_rejected_alter_proof_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_content',
            field=models.CharField(choices=[('question', 'question'), ('answer', 'answer'), ('comment', 'comment')], max_length=255),
        ),
    ]
