# Generated by Django 5.0.2 on 2024-03-15 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.answer'),
        ),
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.comment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.question'),
        ),
    ]
