# Generated by Django 5.0.2 on 2024-03-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_report_answer_alter_report_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
